# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
zha_toolkit:

lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Home
      icon: mdi:view-dashboard-variant-outline
      show_in_sidebar: true
      filename: home_dashboard.yaml

recorder:
  commit_interval: 10
  purge_keep_days: 7
  exclude:
    entity_globs:
      - binary_sensor.*_occupancy
      - weather.*
      - sensor.everything_presence_lite*
    domains:
      - automation
    event_types:
      - call_service # Don't record actions

logger:
  default: info
  logs:
    custom_components.zha_toolkit: warning

system_log:
  fire_event: true

api:

bluetooth:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
# scrape: !include scrape.yaml

template:
  - !include template_sensors/daily_weather_forecast.yaml
  - !include template_sensors/hourly_weather_forecast.yaml
  - !include template_sensors/signed_temperature_rate.yaml
  - !include template_sensors/delta_t.yaml
  - !include template_sensors/bubble_module.yaml
  - !include template_sensors/max_daily_cost.yaml

plant:
  Monstera:
    sensors:
      moisture: sensor.monstera_moisture_humidity
      temperature: sensor.monstera_moisture_temperature
      battery: sensor.monstera_moisture_battery
    min_moisture: 10

input_number:
  summer_off_peak:
    name: Summer Off Peak
    initial: 0.39562
    min: 0
    max: 1
    step: 0.00001
    mode: box
  summer_parial_peak:
    name: Summer Partial Peak
    initial: 0.45230
    min: 0
    max: 1
    step: 0.00001
    mode: box
  summer_peak:
    name: Summer Partial Peak
    initial: 0.61418
    min: 0
    max: 1
    step: 0.00001
    mode: box
  winter_off_peak:
    name: Winter Off Peak
    initial: 0.34671
    min: 0
    max: 1
    step: 0.00001
    mode: box
  winter_parial_peak:
    name: Winter Partial Peak
    initial: 0.36057
    min: 0
    max: 1
    step: 0.00001
  winter_peak:
    name: Winter Partial Peak
    initial: 0.38266
    min: 0
    max: 1
    step: 0.00001
    mode: box
# rest:
#   - !include rest.yaml
