# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

zha_toolkit:

lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Home
      icon: mdi:view-dashboard-variant-outline
      show_in_sidebar: false
      filename: home_dashboard.yaml
      require_admin: true

recorder:
  commit_interval: 10
  purge_keep_days: 7
  exclude:
    entity_globs:
      - binary_sensor.*_occupancy
      - weather.*
      - sensor.everything_presence_lite*
      - sensor.sensy_one*
    domains:
      - automation
    event_types:
      - call_service # Don't record actions

logger:
  default: info
  logs:
    custom_components.zha_toolkit: warning

system_log:
  fire_event: true

api:

bluetooth:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
input_number: !include input_numbers.yaml
# scrape: !include scrape.yaml

template:
  - !include template_sensors/daily_weather_forecast.yaml
  - !include template_sensors/hourly_weather_forecast.yaml
  - !include template_sensors/signed_temperature_rate.yaml
  - !include template_sensors/delta_t.yaml
  - !include template_sensors/bubble_module.yaml
  - !include template_sensors/max_daily_cost.yaml
  - !include template_sensors/max_percent_cost.yaml
  - !include template_sensors/ai_prompt_output.yaml

plant: !include simple_plant/monstera.yaml
# rest:
#   - !include rest.yaml

# Uncomment this if you are using SSL/TI
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
