# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
zha_toolkit:

lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Home
      icon: mdi:view-dashboard-variant-outline
      show_in_sidebar: true
      filename: home_dashboard.yaml

recorder:
  commit_interval: 10
  purge_keep_days: 7
  exclude:
    entity_globs:
      - binary_sensor.*_occupancy
      - weather.*
      - sensor.everything_presence_lite*
    domains:
      - automation
    event_types:
      - call_service # Don't record actions

logger:
  default: info
  logs:
    custom_components.zha_toolkit: warning

system_log:
  fire_event: true

api:

bluetooth:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
# scrape: !include scrape.yaml

template:
  - !include template_sensors/daily_weather_forecast.yaml
  - !include template_sensors/hourly_weather_forecast.yaml
  - !include template_sensors/signed_temperature_rate.yaml
  - !include template_sensors/delta_t.yaml
# rest:
#   - !include rest.yaml
