- platform: average
  name: "Whirlpool Dishwasher Average Power"
  unique_id: 5739e-12358f-ghkdl-1857jg8d1ld908
  duration: 600
  entities:
    - sensor.whirlpool_dishwasher_power
- platform: average
  name: "Whirlpool Washing Machine Average power"
  unique_id: 5739e-12358f-ghkdl-1830jg8d1kd908
  duration: 600
  entities:
    - sensor.whirlpool_washing_machine_power

- platform: apparent_temperature
  name: "Family Room Apparent Temperature"
  unique_id: family_room_apparent_temperature
  source:
    - sensor.family_room_temp_temperature
    - sensor.family_room_temp_humidity

- platform: apparent_temperature
  name: "Kitchen Apparent Temperature"
  unique_id: kitchen_apparent_temperature
  source:
    - sensor.kitchen_temp_temperature
    - sensor.kitchen_temp_humidity

- platform: apparent_temperature
  name: "Office Apparent Temperature"
  unique_id: office_apparent_temperature
  source:
    - sensor.office_temp_temperature
    - sensor.office_temp_humidity

- !include subreddit.yaml
