blueprint:
  name: Thermostat Extract Target Temperature
  description: Pulls the target temperature attribute from a climate device
  domain: template
  source_url: https://github.com/georgefahmy/home-assistant/blob/main/blueprints/extract_thermostat_target_temperature.yaml
  input:
    reference_entity:
      name: Climate Entity to Extract Target
      description: The Climate device to extract the target temperature from
      selector:
        entity:
          domain:
          - climate
          multiple: false
variables:
  reference_entity: !input reference_entity
sensor:
  state: '{{ states.climate.upstairs_thermostat.attributes.temperature }}'
  availability: '{{ states(reference_entity) not in (''unknown'', ''unavailable'')
    }}'
