sensor:
  - name: Signed Average Temperature Rate
    unique_id: signed_average_temperature_rate
    state: "{{ states('sensor.average_temperature_rate') }}"
    unit_of_measurement: °F/h
    icon: "{{ (this.state > '0.0') | iif('mdi:trending-up', 'mdi:trending-down') }}"
