substitutions:
  name: esp32-bluetooth-proxy-6bbec4
  friendly_name: Guest Room Bluetooth Proxy 6bbec4
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: UxJTCwiWqMCoNcVXJfjRYHgCVw+R2BR8DNaUbN51LXM=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
