substitutions:
  name: esp32-bluetooth-proxy-6bec98
  friendly_name: Family Room Bluetooth Proxy 6bec98
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: Oy7pikJlRqOkRLdw9Tiu12t2rJ6UUvIB3SQKH0rFqQ0=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
